### PR TITLE
Update PiOS; add arm64 config

### PR DESCRIPTION
**Pull request by Pernat1y**
Update Raspberry Pi OS
Add Raspberry Pi OS config for arm64

### CODE REVIEW

**Review by unixabg — COMMENTED** [review]
Greetings, thank you for the pr. I will want to test this but looks ok. I notice you are enabling some features that be generic examples I generally leave off such as export _NEWLUKSUUID="yes". I am going to believe that you have actively tested. So if passes for me I will leave the example as is with the features on.

**Review by unixabg — COMMENTED** [review]
Oxford (or serial) comma is my preferred format. I believe you have adjusted to AP style. https://www.grammarly.com/blog/what-is-the-oxford-comma-and-why-do-people-care-so-much-about-it/

**Review by unixabg — COMMENTED** [review]
I believe this commit unnecessary since that variable information can be included with the ${_LUKSEXTRA} for any options not already provided.

**Comment by unixabg** [comment]
Greetings,
Allow me to pull parts of this in and we sync back up on next-4.x branch. From there we can tune things keeping the pr smaller helps me.
Again thank you for the code.

**Comment by Pernat1y** [comment]
Regarding _NEWLUKSUUID, it can be set back to "no". Not much of the difference in result.

> Greetings, Allow me to pull parts of this in and we sync back up on next-4.x branch. From there we can tune things keeping the pr smaller helps me. Again thank you for the code.
Sure, thanks.

**Review by unixabg — COMMENTED** [review]
On this one, I will have to do some reading and it can be tested with the _LUKSEXTRA

**Comment by unixabg** [comment]
Greetings,
I have attempted to merge most of this pr . If you would update to my next-4.x branch and test that would be great. Again thanks for the code and you can see how I broke down to smaller commits.

**Pull request closed without merging**
