### PR TITLE
Fixes and small improvements

### PR DESCRIPTION
**Pull request by splitstrikestream**
There where small bugs: specially things that would not work correctly if not root (using sudo).

> Do you do irc? If so I go over to #kali-linux and irc would be better for me than using these threads on PR. 

Not in the last 20 years. Will try to recap, and will let you know.

> Also if you make more changes please do:
> 
> pull --rebase
> 
> before push. Also I test then unify some things then if works merge to master.

Did add a remote, fetched and rebased from it, but was already updated.

I think you can do your tests now. I am just finishing one last round, but everything seems ok.

### CODE REVIEW

**Comment by splitstrikestream** [comment]
I recommend you to test using the optional sshhub hooks. Registration is super simple at sshhub.de
Then set the _SSHHUB_USERNAME (and _SSHHUB_LOCAL_KEYFILE if you are not using the default .ssh/id_rsa key for that)

**Comment by unixabg** [comment]
Greetings,
I have setup pristine vm with latest kali for testing. I am going to harmonize and unify some things. I do a test run on almost every change. So it will take some time, but the code looks in really good order. One thing that did catch my eye today that I am concerned about is the file:

example-kali-complete/openvpn.zip

from a previous commit. It seems to reveal things that should not be there. If that is the case I will need to sanitize that file from the repository.

**Comment by splitstrikestream** [comment]
ow, please do sanitize it :fearful:

**Comment by splitstrikestream** [comment]
i did `~/downloads/bfg-1.13.0.jar --delete-files openvpn.zip` and `git reflog expire --expire=now --all && git gc --prune=now --aggressive` on my side.

**Pull request merged**
