### PR TITLE
Fix spellcheck warnings (SC2086, SC2006) in *.fns, *.hook, *.conf, stage2-otherscript.sh, mini-kali-image and cryptmypi.sh files.

### PR DESCRIPTION
**Pull request by gemesa**
I ran spellcheck on the code base and fixed the following warnings:
- [SC2086](https://www.shellcheck.net/wiki/SC2086) - Double quote to prevent globbing and word splitting.
- [SC2006](https://www.shellcheck.net/wiki/SC2006) - Use $(...) notation instead of legacy backticked \`...\`.

This is a refactor, there is no functional change.

### CODE REVIEW

**Comment by gemesa** [comment]
I did not run any tests yet tbh but I can do it. Is it enough to check if the system boots? Should I attach some logs here?

**Comment by unixabg** [comment]
Greetings,
With a change like I would test most of the Kali images. The sshhub needs the generic jump host tested. I do not test personally the iodine setup. But if all else works I can request that from my iodine tester. I am open to ideas on a test build simulation model for all/most of the images to be tested automatically. Please know I will look through this in greater detail upon next sitting to work on the project. Thanks again for the pr and your willingness to test.

**Comment by gemesa** [comment]
> The sshhub needs the generic jump host tested.

Can you describe how to test this exactly? I do not use any of the Kali images, just the pios ones. Also, I can not locate the sshhub.de website with google.

**Comment by unixabg** [comment]
Greetings,
So when I test, I build each test image and deploy on rpi3 or rpi4 and manually make sure it boots and unlocks. The original code for sshjump was contributed for the sshhub.de . I made it more general with this commit 5caee8e2dd9 . If generic builds work I can setup and test the sshjump part. It in general takes a lot of time to build and test the examples. Since you use the PiOS images, just start there and make sure they build and unlock correctly.

**Comment by gemesa** [comment]
I am too busy to work on this, will reopen and continue when I will have more time.

**Pull request closed without merging**
